{:user {:plugins [[lein-pprint "1.1.2"]
                  [lein-kibit "0.1.2"]
                  [lein-codox "0.9.5"]
                  [lein-simpleton "1.3.0"]]
        :dependencies [[org.clojure/clojure "1.8.0"]
                       [org.clojure/data.json "0.2.6"]
                       [org.clojure/data.xml "0.0.8"]
                       [org.clojure/tools.namespace "0.2.11"]
                       [com.stuartsierra/component "0.3.1"]
                       [org.clojars.hozumi/clj-commons-exec "1.2.0"]
                       [dire "0.5.4"]
                       [clj-time "0.12.0"]
                       [clojusc/twig "0.2.1"]
                       [slamhound "1.5.5"]
                       [clj-gdal "0.4.0-ALPHA"]]}}
