FROM usgseros/ubuntu-gis
MAINTAINER USGS LCMAP http://eros.usgs.gov

RUN apt-get install -y python python3 python-pip
RUN apt-get install -y python-gdal python3-gdal python-otb
RUN apt-get install -y ipython ipython-notebook ipython-notebook-common \
    ipython3 ipython3-notebook
RUN apt-get install -y python-scipy python-numpy python-pyproj python-h5py \
    python3-scipy python3-numpy python3-pyproj python3-h5py
