{:user {:plugins [[lein-pprint "1.1.1"]
                  [lein-kibit "0.1.2"]
                  [lein-codox "0.9.1"]
                  [lein-simpleton "1.3.0"]]
        :dependencies [[org.clojure/clojure "1.8.0"]
                       [org.clojure/data.json "0.2.6"]
                       [org.clojure/data.xml "0.0.8"]
                       [org.clojure/tools.logging "0.3.1"]
                       [org.clojure/tools.namespace "0.2.11"]
                       [com.stuartsierra/component "0.3.0"]
                       [org.clojars.hozumi/clj-commons-exec "1.2.0"]
                       [ch.qos.logback/logback-classic "1.1.3"]
                       [dire "0.5.3"]
                       [clj-time "0.11.0"]
                       [slamhound "1.5.5"]
                       [element84/clj-gdal "0.3.2"]]}}
